#!/bin/sh
set -e

lb config noauto \
    --system live \
    --distribution bookworm \
    --debian-installer none \
    --archive-areas "main contrib non-free non-free-firmware" \
    --apt-recommends false \
    --binary-images iso-hybrid \
    --bootloader grub-efi \
    --uefi-secure-boot disable \
    --memtest none \
    --iso-application "NarobOS" \
    --iso-publisher "NarobOS Project" \
    --iso-volume "NarobOS 1.0" \
    --image-name "narobos-1.0-amd64" \
    --linux-flavours amd64 \
    --firmware-binary true \
    --firmware-chroot true \
    --mirror-bootstrap "http://deb.debian.org/debian/" \
    --mirror-chroot "http://deb.debian.org/debian/" \
    "${@}"
